# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e5f757669c39d6c21407b9fbb7f7b8b3059de012ab0b65166be92e431cdf8ea2d056c4f8d022c6ccc1cc33e91d8379be31c74df581e110c93444c816905a11d

test:
  secret_key_base: 326fb7ed4f9589e596603fe758b51b595cbef33168b246fea12e0e344d893cc158d2eaaf4365dcbe53e1a1153cdf86819f86f6e5c60b864b599b58ef0eb17026

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
